name: Deploy React Portfolio

# Controla cuándo se ejecutará el workflow
on:
  # Se ejecuta en push a la rama principal
  push:
    branches: [ main ]
    paths:
      - 'front/**'  # Solo se activa cuando hay cambios en la carpeta front
  
  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos necesarios para acciones de GitHub
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    
    steps:
      # Paso 1: Checkout del código
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      
      # Paso 2: Configurar Node.js
      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'
      
      # Paso 3: Navegar a la carpeta front e instalar dependencias
      - name: Install Dependencies 📦
        run: |
          cd front
          npm ci
      
      # Paso 4: Generate Blog Posts Manifest 📝
      - name: Generate Blog Posts Manifest 📝
        run: |
          cd front
          npm run generate-manifest
      
      # Paso 5: Verify Blog Structure 🔍
      - name: Verify Blog Structure 🔍
        run: |
          cd front
          echo "=== Blog Directory Structure ==="
          ls -la public/blog/ || echo "Blog directory not found"
          echo "=== Posts Manifest ==="
          cat public/blog/posts-manifest.json || echo "Manifest not found"
          echo "=== Posts Directory ==="
          find public/blog/posts -name "*.md" || echo "No markdown files found"
      
      # Paso 6: Construir la aplicación
      - name: Build 🔧
        run: |
          cd front
          npm run build
        env:
          CI: false  # Evita que los warnings detengan la compilación
      
      # Paso 7: Verify Build Contents 🔍
      - name: Verify Build Contents 🔍
        run: |
          cd front
          echo "=== Build Directory Structure ==="
          ls -la build/
          echo "=== Blog Assets in Build ==="
          ls -la build/blog/ || echo "Blog assets not found in build"
      
      # Paso 8: Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: front/build  # La carpeta que contiene los archivos compilados
          branch: gh-pages     # La rama donde se desplegará
          clean: true          # Elimina archivos de despliegues anteriores