name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask user-agents plotly pandas gunicorn

      - name: Create static build
        run: |
          mkdir -p _site
          cp -r assets _site/
          cp -r src/* _site/
          # Asegurarse de que index.html esté en la raíz
          if [ -f _site/index.html ]; then
            echo "index.html found in correct location"
          else
            echo "Moving index.html to root"
            cp src/index.html _site/
          fi

      - name: Fix paths in HTML files
        run: |
          find _site -type f -name "*.html" -exec sed -i 's/src\/css/css/g' {} +
          find _site -type f -name "*.html" -exec sed -i 's/src\/js/js/g' {} +
          find _site -type f -name "*.html" -exec sed -i 's/\.\.\/assets/assets/g' {} +

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4